# Yarn v2 Configuration
#
# References:
#
# - https://yarnpkg.com/configuration/yarnrc

defaultSemverRangePrefix: ''

enableInlineBuilds: true

nodeLinker: node-modules

npmRegistryServer: 'https://registry.yarnpkg.com'

npmScopes:
  flex-development:
    npmAlwaysAuth: true
    npmAuthToken: '${PAT_GPR}'
    npmRegistryServer: 'https://npm.pkg.github.com'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.0.0-rc.2.cjs
