/**
 * @file Enums - NotesType
 * @module grease/enums/NotesType
 */

/**
 * Types of release notes generated by the `notes` lifecycle.
 */
export enum NotesType {
  /**
   * Generate notes in birthday (first release) format.
   */
  BIRTHDAY = 'birthday',

  /**
   * Generate empty release notes.
   */
  BLANK = 'blank',

  /**
   * Generate release notes from `CHANGELOG` excerpt.
   */
  CHANGELOG = 'changelog',

  /**
   * Skip release note generation.
   */
  NULL = 'null'
}
