# Release Branch
#
# Execute version bump, changelog, and pull request operations on release branch creation.
#
# References:
#
# - https://cli.github.com/manual/gh_pr_create
# - https://docs.github.com/actions/learn-github-actions/contexts
# - https://docs.github.com/actions/learn-github-actions/expressions
# - https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#create
# - https://docs.github.com/actions/using-workflows/workflow-commands-for-github-actions
# - https://docs.github.com/webhooks-and-events/webhooks/webhook-events-and-payloads#create
# - https://github.com/actions/checkout
# - https://github.com/actions/setup-node
# - https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#yarn2-configuration
# - https://github.com/hmarr/debug-action
# - https://github.com/kaisugi/action-regex-match
# - https://regex101.com/r/OwpOr2

---
name: release-branch
on: create
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  preflight:
    if: startsWith(github.ref_name, 'release/')
    permissions:
      contents: read
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.message.outputs.result }}
      tag: ${{ steps.tag.outputs.result }}
      version: ${{ steps.version.outputs.match }}
    steps:
      - id: debug
        name: Print environment variables and event payload
        uses: hmarr/debug-action@v2.1.0
      - id: checkout
        name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v4.1.1
        with:
          persist-credentials: false
          ref: ${{ github.ref }}
      - id: version
        name: Get release version
        uses: kaisugi/action-regex-match@v1.0.0
        with:
          regex: |
            (?<=release\/)(?<version>(?<major>0|[1-9]\d*)\.(?<minor>0|[1-9]\d*)\.(?<patch>0|[1-9]\d*)(?:-(?<prerelease>(?:0|[1-9]\d*|\d*[A-Za-z-][\dA-Za-z-]*)(?:\.(?:0|[1-9]\d*|\d*[A-Za-z-][\dA-Za-z-]*))*))?(?:\+(?<metadata>[\dA-Za-z-]+(?:\.[\dA-Za-z-]+)*))?$)
          text: ${{ github.ref_name }}
      - id: tag
        name: Get release tag
        run: |
          echo "result=$(jq .tagprefix grease.config.json -r)${{ steps.version.outputs.match }}" >>$GITHUB_OUTPUT
      - id: message
        name: Get release message
        run: |
          echo "result=release: ${{ steps.tag.outputs.result }}" >>$GITHUB_OUTPUT
  prepare:
    if: needs.preflight.outputs.version != ''
    needs: preflight
    permissions:
      contents: write
      packages: read
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      HUSKY: 0
    steps:
      - id: checkout
        name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - id: gpg-import
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6.0.0
        with:
          git_commit_gpgsign: true
          git_config_global: true
          git_push_gpgsign: false
          git_user_signingkey: true
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          trust_level: 5
      - id: yarn
        name: Install dependencies
        run: yarn --immutable
      - id: build
        name: Build project
        env:
          NODE_NO_WARNINGS: 1
        run: yarn build
      - id: bump
        name: Bump manifest version to ${{ needs.preflight.outputs.version }}
        run: node ./dist/cli.mjs bump -w ${{ needs.preflight.outputs.version }}
      - id: changelog
        name: Add CHANGELOG entry for ${{ needs.preflight.outputs.tag }}
        run: node ./dist/cli.mjs changelog && node ./dist/cli.mjs changelog -sw
      - id: commit
        name: Commit release preparation
        run: |
          git add CHANGELOG.md package.json
          git status
          git commit -s -m 'release: ${{ needs.preflight.outputs.tag }}'
          git log --show-signature 'HEAD^..HEAD'
      - id: push
        name: Push release preparation
        run: git push --no-verify
  pr:
    needs:
      - preflight
      - prepare
    env:
      GITHUB_TOKEN: ${{ secrets.PAT_REPO }}
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}
      - id: pr
        name: Create pull request
        run: |
          gh pr create --title='${{ needs.preflight.outputs.message }}' --label=scope:release --assignee=@${{ github.actor }} --body='## Description

          <!-- A clear and concise description of your changes. -->

          - bumped manifest version to `${{ needs.preflight.outputs.version }}`
          - added `CHANGELOG` entry for `${{ needs.preflight.outputs.tag }}`

          ## Linked issues

          <!--
          A list of linked issues and/or pull requests.

          - <closes|fixes|resolves> #<issue-number>
          - <prereleases|releases> #<pr-number>
          -->

          N/A

          ## Related documents

          <!-- A list of related documents (e.g. docs, proposals, specs, etc), if any. -->

          N/A

          ## Additional context

          <!--
          Include additional details here. Be sure to note if any tolerable vulnerabilities or warnings have been introduced.
          -->

          N/A

          ## Submission checklist

          - [x] self-review performed
          - [x] tests added and/or updated
          - [x] documentation added or updated
          - [x] new, **tolerable** vulnerabilities and/or warnings documented, if any
          - [x] [pr naming conventions][1]

          [1]: https://github.com/${{ github.repository }}/blob/main/CONTRIBUTING.md#pull-request-titles'
